name: "logisense_uoih"
version: "0.1.0"
config-version: 2

profile: "logisense_iceberg"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  run_date: "{{ modules.datetime.date.today().isoformat() }}"

models:
  logisense_uoih:
    gold:
      +materialized: incremental
      +incremental_strategy: merge
      +unique_key: ["facility_id", "date"]
      +file_format: iceberg
      +table_type: iceberg
